name: Validation
on:
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install pydantic==2.11.4 rich==14.0.0 pandas==2.2.3

      - name: Install editable package
        run: |
          pip install -e .

      - name: Run validation script
        run: |
          python src/backend/validation/validate.py