x-global-environment: &global-environment
  env_file:
    - .env

services:
  lakefsdb:
    container_name: lakefs_db
    image: treeverse/lakefs:1.7.0
    ports:
      - 8001:8000
    environment:
      LAKEFS_INSTALLATION_USER_NAME: "admin"
      LAKEFS_INSTALLATION_ACCESS_KEY_ID: ${ACCESS_KEY}
      LAKEFS_INSTALLATION_SECRET_ACCESS_KEY: ${SECRET_KEY}
      LAKEFS_DATABASE_TYPE: "local"
      LAKEFS_AUTH_ENCRYPT_SECRET_KEY: "wait"
      LAKEFS_BLOCKSTORE_TYPE: "local"
    <<: *global-environment
    networks:
      - PrefectNetwork
    volumes:
      - ./data/:/home/lakefs/
  
  ### Prefect Database
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: ["server"]
    <<: *global-environment
    networks:
      - PrefectNetwork

  ### Prefect Server API and UI
  server:
    container_name: prefect
    image: prefecthq/prefect:3-python3.13
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["server"]
    <<: *global-environment
    networks:
      - PrefectNetwork
  ## Prefect Worker
  worker:
    # image: prefecthq/prefect:3-python3.13
    build:
      context: .
      dockerfile: config/docker/Dockerfile.worker
    restart: always
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "worker", "start", "-p", "x-worker"]
    working_dir: "/root/flows"
    volumes:
      - "./src/backend:/root/flows/src/backend"
      - "./data/from_prefect:/root/flows/data/from_prefect"
      - "./config/logging/modern_log.py:/root/flows/config/logging/modern_log.py"
      - "./config/auth/twitter_auth.json:/root/flows/config/auth/twitter_auth.json"
      - "./config/path_config.py:/root/flows/config/path_config.py"
      - "./pyproject.toml:/root/flows/pyproject.toml"
      - "./.env:/root/flows/.env"
    environment:
      - PREFECT_API_URL=http://server:4200/api
    profiles: ["worker"]
    networks:
      - PrefectNetwork
  ### Prefect CLI
  cli:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.cli
    entrypoint: "bash"
    working_dir: "/root/flows"
    volumes:
      - "./src/backend:/root/flows/src/backend"
      - "./data/from_prefect:/root/flows/data/from_prefect"
      - "./config/logging/modern_log.py:/root/flows/config/logging/modern_log.py"
      - "./config/auth/twitter_auth.json:/root/flows/config/auth/twitter_auth.json"
      - "./config/path_config.py:/root/flows/config/path_config.py"
      - "./pyproject.toml:/root/flows/pyproject.toml"
      - "./.env:/root/flows/.env"
      - "./start-prefect.sh:/root/flows/start-prefect.sh"
    environment:
      - PREFECT_API_URL=http://server:4200/api
    profiles: ["cli"]
    networks:
      - PrefectNetwork

volumes:
  prefect:
  db:

networks:
  PrefectNetwork:
